- hosts: hosts
  user: ubuntu
  vars_prompt:
    - name: 'ssh_private_key'
      prompt: "Enter path to SSH private key to copy to jump box"
  tasks:
    - name: Ensure private key
      copy:
      src: "{{ ssh_private_key }}"
      path: $HOME/.ssh/phobos_key
      mode: 400

    - name: Ensure contents of ssh config
      blockinfile:
        path: $HOME/.ssh/config
        block: |
          # Phobos
          Host 172.20.*
              User ubuntu
              IdentityFile $HOME/.ssh/phobos_key
              StrictHostKeyChecking no
              UserKnownHostsFile /dev/null
              ServerAliveInterval 180

    - name: Ensure contents of bashrc
      lineinfile:
        path: $HOME/.bashrc
        line: "{{ item }}"
      with_items:
        - "eval $(ssh-agent -s)"
        - "ssh-add ~/.ssh/id_rsa"
        - "source $HOME/openrc.sh"

    - name: Ensure contents of openrc.sh
      template:
        src: openrc.sh.j2
        dest: $HOME/openrc.sh
